version: 2

sources:
  - name: gz_raw
    schema: gz_raw_data
    description: "First dbt model"
    tables:
      - name: sales
        identifier: raw_gw_sales
        tests:
          - unique:
              column_name: (orders_id ||'_'|| pdt_id)

      - name: product
        identifier: raw_gz_product
        description: product of greenweez
        columns:
          - name: products_id
            description: Primary key of the table
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        description: ship of greenweez
        columns:
          - name: orders_id
            description: Primary key of the table
            tests:
              - unique
              - not_null
      - name: adwords
        identifier: raw_gz_adwords
        description: campaign adwords
        tests:
          - unique:
              column_name: (date_date ||'_'|| campaign_key)
      - name: bing
        identifier: raw_gz_bing
        description: campaign bing
        tests:
          - unique:
              column_name: (date_date ||'_'|| campaign_key)
      - name: criteo
        identifier: raw_gz_criteo
        description: campaign criteo
        tests:
          - unique:
              column_name: (date_date ||'_'|| campaign_key)
      - name: facebook
        identifier: raw_gz_facebook
        description: campaign facebook
        tests:
          - unique:
              column_name: (date_date ||'_'|| campaign_key)
       




